### ISSUE TITLE
Bottle return point (Depozīta punkti) locations

### ISSUE THREAD

**Issue by HellMapGoesCoding** [OSMLatvija/Osmalyzer#21]
https://www.depozitapunkts.lv/

https://projects.kartes.lv/dio_api/

**Comment by markalex2209** [comment]
Actual list of punkts is requested from [here](https://projects.kartes.lv/dio_api/) (It's behind 302, but I think we should use this URL too).

Points exist in three types: 
- A - automated, mapped as `amenity=recycling` or `amenity=vending_machine vending=bottle_return`,
- M - manual, unclear how should be mapped. Probably some additional tag on `shop=*`, but need a clarification.
- B - Beramtaromāts. No clue what it is. Based on quick search, I think this is a first test batch of automated points installed, but need a confirmation.

**Comment by markalex2209** [comment]
We started implementation. Have a question regarding JSON parsing: was the decision not to use a parser a conscious choice, or it just happened?
And if latter, how open are you to incorporating an actual parser into project? And do you have any preferences?
