### ISSUE TITLE
Post offices

### ISSUE THREAD

**Issue by HellMapGoesCoding** [OSMLatvija/Osmalyzer#31]
- [X] Post code analyzing
- [X] Post offices from OSM
- [x] Post offices from LP
- [x] Compare OSM to LP post offices
- [X] Post codes from OSM
- [x] Post codes from LP
- [x] Compare OSM to LP post codes occurrences
- [X] Post code regions from OSM
- [ ] Post code regions from LP
- [ ] Compare expected to actual regions

**Comment by markalex2209** [comment]
Data for all objects that are shown on LP site is retrieved from https://pasts.lv/ajax/module:post_office/

Data there is in somewhat strange format:
```json
{"all":"<serialised json array of POIs>","count":1287}
```
And POIs in that array look like this:
```json
{
    "tmpLat":57.077432765182,
    "tmpLong":24.323845390354,
    "tmpName":"\\u0100da\\u017eu pasta noda\\u013ca",
    "tmpNameFull":"\\u0100da\\u017eu pasta noda\\u013ca LV-2164",
    "tmpAddress":"Gaujas iela 11, \\u0100da\\u017ei, \\u0100da\\u017eu nov., LV-2164",
    "tmpCategory":1,
    "tmpDistrict":"\\u0100da\\u017eu nov.",
    "tmpPhone":"67008001",
    "tmpService":"LV-2164",
    "tmpImage":null,
    "tmpWork":"P 8:00-18:00<br \\/>O 8:00-18:00<br \\/>T 8:00-19:00<br \\/>C 8:00-18:00<br \\/>P 8:00-18:00<br \\/>S -<br \\/>Sv -<br \\/>",
    "tmpPayment":"1",
    "tmpFilterOut":false,
    "tmpMarker":null,
    "tmpInfo":null
},
```
As far as I can tell `tmpCategory` stands for category of object to be shown on the map, where
- 1 - post office,
- 2 - Circle K (don't know why they are here)
- 4 - post box,
- 5 - parcel lockers,
- 6 - I'm not sure, but based on the site itself, probably something called "Pasta pakalpojumi pēc pieprasījuma". Crude translation "Postal services on request", not sure what this means exactly.

**Comment by markalex2209** [comment]
This information will probably also be useful in #7

**Comment by markalex2209** [comment]
I see a lot of the "unexpected" post offices being reported. At least some of them seems to be locations corresponding to type 6.

Have you reached some understanding what those are, and how they are expected to be mapped on OSM?
